build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1

processors:
  active: true
  exclude:
    - 'FunctionCountProcessor'

console-reports:
  active: true
  exclude:
    - 'FindingsReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'

style:
  MagicNumber:
    active: true
    ignoreNumbers: [-1,0,1,2]
  NamingRules:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
    functionPattern: '^[a-z][A-Za-z0-9]*$'
    variablePattern: '^[a-z][A-Za-z0-9]*$'

complexity:
  LargeClass:
    active: true
    threshold: 500
  LongMethod:
    active: true
    threshold: 50
  LongParameterList:
    active: true
    threshold: 5

potential-bugs:
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  UnsafeCast:
    active: true

comments:
  CommentOverPrivateFunction:
    active: false
